In [80]:
%reload_ext autoreload
%autoreload 2
import numpy as np, sys, os, pandas as pd,json, os
sys.path.insert(1, '../../')
from getting_data import read_conf

In [81]:
_, samples, __ = read_conf('.')

sv = []
bv = []

for sample_key in samples.keys():
    sample_tasks = samples[sample_key]
    for task in sample_tasks:
        rg = task['range']
        m_file = os.path.join('scores', f"{sample_key}_shap_sampling_{rg[0]}_{rg[1]}.npz")
        if os.path.exists(m_file):
            ld = np.load(m_file)
            
            shap_values = ld['shap_values']
            base_values = ld['base_values']
            
            sv.extend(shap_values)
            bv.extend(base_values)

In [82]:
for arr in sv:
    print(arr)

[-0.71969641  2.29092287  0.          0.         -0.67590413 -0.15244064]
[-0.61513385 12.79816914  0.          0.          0.37645837 -0.10212747]
[-2.64762803 -5.85143355 -0.26644749  0.          0.58455945 -0.10473596]
[ 6.3251833  -3.31235162 -0.08595746  0.          0.4427309   0.08354999]
[ 2.86207873 10.60549172  0.          0.          0.05908199 -0.04562118]
[-2.55278855 -6.13526271 -0.08549287  0.          0.58253983 -0.15206497]
[-0.94013305  2.57649074  0.          0.          0.12312017  0.01509808]
[ 2.78678649  0.29428172 -0.08575498  0.          0.12609335  0.03485599]
[-2.5604339  -6.12885234 -0.08869118  0.         -0.51413065 -0.08532433]
[-0.87513386  2.61323476 -0.14209858  0.          0.13185057  0.30894031]
[-2.70215499 -6.10296314  0.          0.          0.14705719 -0.0283421 ]
[-2.59401752 -6.04491839 -0.08687674  0.          0.10570985 -0.17581115]
[ 8.40366963  6.3044114   0.          0.         -0.13624269  0.44080273]
[-2.45644943 -6.41750384  0.          

In [83]:
for arr in bv:
    print(arr)

-7.083572130456701
-7.083572130456701
